a = 1

try:
    ...
except Exception as a:
    ...

print(a)
